### ISSUE TITLE
[DOC ]Folder structure visible on batch example

### ISSUE THREAD

**Issue by ileppe** [qMRLab/qMRLab#158]
My personal folder is showing up on the batch examples in the documentation...
@agahkarakuzu, `GenerateDocumentation.m`  by default creates the `Data` folder in `qMRLab`. Do you think we can modify this so that we can provide and arbitrary location for the data and batch examples? I realize that this will be a bit more annoying in terms for directory structure and will affect files like `auto_toc.py`.

**Comment by agahkarakuzu** [comment]
@ileppe Personal folders are no longer visible on batch examples dbb595c53cc0cf7c192dd0e6a3790a56d3a6c7ea. I've made changes under your error-catch branch, given that it was a minor tweak.

For batch examples, unless a directory is passed as an input argument, function will ask for one (user end). At the developer end, for example, we passed temporary directories to qMRgenBatch in   [BatchExample_test](https://github.com/neuropoly/qMRLab/blob/master/Test/MoxUnitCompatible/BatchExample_test.m). 

It is possible that we can take a similar approach for `GenerateDocumentation.m`. To do this, we may need @gab-berest's help because Data folder is hardcoded in his python script e.g. `for root_s, dirs_s, files_s in os.walk('../Data'): `. We can either think of passing temp folder directory to the python script during its function call, or keep the function void and make it read temp directory from a temporary text file, which is possibly to be saved under a gitignore folder. I need @gab-berest's vision to decide how to proceed.

**Comment by gab-berest** [comment]
@agahkarakuzu Ok, so if I understand, we want to specify a different folder path for GenerateDocumentation.m that would be saved in a temporary text file. Is that it?

**Comment by agahkarakuzu** [comment]
@gab-berest yes, we just need some flexibility to change directory from .`./Data` to `some other directory`.  Reading `some other directory`  from a text file or passing it as an argument is up to your convenience. Which one would you prefer? 

Is there anything that we need to be careful not to break anything functional in doing so?

**Comment by agahkarakuzu** [comment]
@gab-berest Tangential to this discussion, I would like to know if we have dependencies for documentation generation other than those I mentioned [here](https://github.com/neuropoly/qMRLab/wiki/Guideline:-Documentation)?

**Comment by gab-berest** [comment]
@agahkarakuzu I think the easier way would be to have a temporary text file generated that indicates the path. So the python script would only need to recover the path from this file.

**Comment by agahkarakuzu** [comment]
@gab-berest alright, I've branched out from @ileppe 's catch-error branch for this one. I will update you soon about the convention I will set in `GenerateDocumentation`. Data is already in gitignore, but having this functionality would be nice.

**Comment by gab-berest** [comment]
@agahkarakuzu Perfect. As soon as I can, I'll update the python script.

**Comment by gab-berest** [comment]
@agahkarakuzu So I checked out on the branch you specified and updated the auto_TOC.py file. On my end, the py file works fine with the temp folder. However, when I run GenerateDocumentation.m, an error appears about QMRgenbatch and qMRUsage and stops the script for noddi. I don't know if it's normal and I didn't change anything in this script.
Can you please help for this and also test the auto_TOC.py script to see if it works on another machine than mine.

**Comment by agahkarakuzu** [comment]
@gab-berest Thank you for quick action. Of course, you can commit on my branch. 

I will check it on my local. First, I need to have documentation dependencies. I opted to document them [here](https://github.com/neuropoly/qMRLab/wiki/Guideline:-Documentation) (on dependencies section). Can you confirm if it is a complete list?

**Comment by gab-berest** [comment]
@agahkarakuzu Hi, I just commited my changes to auto_TOC.py. For the dependencies, I think it's all we need. @ileppe second thougths on the dependencies?

**Comment by tanguyduval** [comment]
solved
