### ISSUE TITLE
new user feedback 

### ISSUE THREAD

**Issue by ravenep** [qMRLab/qMRLab#164]
Hi dev team,

I am a new user of qMRLab and had some questions/comments re: the qmt_spgr module, apologies in advance for any silly mistakes. 

- [x] 1.  For parameter settings, I had no trouble finding/using ‘Load’ for MTdata angle’s and offsets and timing tables. However, if trying to do this within the GUI, I was unable to add additional rows of values (i.e. an 11th row with unique Angle/Offset) - I could only replace values in existing rows.

- [x] 2. In MT_Pulse options - it is sometimes unclear what options are used/required for fitting/sim on the GUI. For example, I selected gaussian pulse, but the Sinc TBW is still available to edit. In help, it says this par is not used for this scenario, but I was initially confused because it was still “open” for edits.

- [x] 3. Tried fitting, got this error. I thought I needed to upload normalized data so did not include the “MToff” contrast. If I do need it, should it be the first contrast? Do I include this in the timings table (i.e., Angle = 0, Offset = 0)

<img width="702" alt="screen shot 2018-02-15 at 11 22 48 am" src="https://user-images.githubusercontent.com/12449573/36286591-5c1011ce-12a8-11e8-842e-6cbaaf15196e.png">

- [ ] 4. I didn't notice the above error until later, but the fitting ran for several days. This was my mistake since I included too many slices, but it might be nice to get a time estimate along with the completion bar.

- [x] 5. More error, possibly still related to my no MToff contrast.

<img width="991" alt="screen shot 2018-02-15 at 11 42 59 am" src="https://user-images.githubusercontent.com/12449573/36286625-7dc653a0-12a8-11e8-82a6-650d36849de0.png">

6. My view! I like the interface
<img width="1672" alt="screen shot 2018-02-15 at 12 01 52 pm" src="https://user-images.githubusercontent.com/12449573/36286660-97458cec-12a8-11e8-8cdd-06453543ec61.png">

**Comment by mathieuboudreau** [comment]
Thanks Erika!

For item 3, I think your data fitted correctly even though it threw that error. Here is the code block that handles/throws this error:

https://github.com/neuropoly/qMRLab/blob/f12bf346a199e5217ca1d4d4af947d6fbe2fa27f/Models/Magnetization_transfer/qmt_spgr.m#L221-L236

It appears that when the devs integrated functionality for a "no-mt" data point (where the FA is 0) in [this commit](https://github.com/neuropoly/qMRLab/commit/f7c4e10d3e6b3b90556035e53985d24e19ccbd9d), they added that warning as a precaution, however they didn't take into account that the original qMTLab paper's work (which is the origin of qMRLab) assumed that the MT data was normalised prior to loading the data into the GUI. From what I can see in the above code block, the code should still fit fine when you normalize it before loading, however we should likely add some kind of checkbox for the user to indicate what type of data they are loading (normalized or unnormalized) so that this error doesn't get thrown for the normalized case.

**Comment by tanguyduval** [comment]
Great feedback, thank you! ok, I can do point 1 and 2.

**Comment by ravenep** [comment]
Hi all, for Issue 5 - I think it is related to fitting single slice vs multi slice. I did both, single slice works as it should - saves FitResults, etc. Multi-slice (I only did two slices this time!) throws the error shown in #5. 

PS I am still using the same version I downloaded 11 days ago.

**Comment by tanguyduval** [comment]
Just solved point 5 in e6ebe1afc68884c839d5f82ad7ff8d98d22c1ff9
In order to close this issue, we just need to add a time estimation (check time in `FitData` by using toc(tStart))

**Comment by agahkarakuzu** [comment]
This issue was moved to https://forum.qmrlab.org/t/new-user-feedback/33
