### ISSUE TITLE
Bloch simulation pipeline

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#190]
Hi @mathieuboudreau @ileppe @tanguyduval 

We previously discussed using Bloch simulations for some models (e.g. t1 and t2 fitting). I suggest using [Brian's simulator](http://mrsrl.stanford.edu/~brian/bloch/) for this purpose, given that it  is quite easy to understand, well documented and not introducing too much complexity.

The core library is consisted of 5 m-files `xrot.m` `yrot.m` `zrot.m` `throt.m` and `freeprecess.m`. For each sequence there will be one `sequence_name_signal` function that synthesizes signal with respect to the selected sequence parameters. 

Do you prefer changes in the scope of `function Smodel = equation(obj, x)`  to substitute analytically synthesized signals with bloch simulated signals (`sequence_name_signal`) or defining a new method such as `function Smodel = blochSignal(obj, x)` ? Would latter option require too many additional changes for compatibility @tanguyduval ? 

I've added Brian's simulator to the external sources on my new branch 90dd7d844e7af6215a9119760c1e9efa0684bdf4. However, library does not have a license.txt. 

Best,
Agah

**Comment by mathieuboudreau** [comment]
@agahkarakuzu I'd like to have both features in the models; simulate signal through equations **or** do Bloch simulations to generate the signal. For some purposes/people, Bloch simulations may be overkill, and simulating through the analytical equations (e.g. and then adding noise) may be sufficient. The other issue is that just doing a Bloch simulation, while more general, may not give the specific features users want. For example, they may want extend the Bloch simulations to simulate an exact pulse sequence (with all the gradients and RF pulses).

So I'd suggest defining a new method to the models like you suggested, i.e. Smodel = blochSignal(obj, x) to retain both features, which I see both as being extremely valuable to the community and qMRLab as a software.

**Comment by agahkarakuzu** [comment]
Thank you for the remarks @mathieuboudreau. I am of one mind about keeping Bloch simulation as a separate component. How do you envision using Bloch simulator as a part of the current simulations (e.g. single voxel curve or sensitivity analysis) or would you rather consider it as a standalone feature?

**Comment by mathieuboudreau** [comment]
I think it would be nice to have just an option box on how you want to generate the signal (Analytical Equaiton or Bloch).

One cool idea with having them both in the same simulating GUI/options, is that hypothetically a user could compare the signal generated from analytical equation against the ones simulated through the Bloch simulator. This could be used for things like testing the approximations of the analytical equation for a particular tissue value set and/or protocol, or looking at the influence of specific pulse sequence components/changes on the signal. Plotting both in the same graph would be a useful feature to think about in the future.

The other benefit of allowing models to simulate the signal through both, is that if a dev implements a new model, she/he could first add the simulation/sensitivity feature by first implementing the analytical equation method (which is easier) so that users have this feature right away, while the Bloch simulator for that model gets implemented later on.

**Comment by agahkarakuzu** [comment]
> One cool idea with having them both in the same simulating GUI/options.

Then multi-echo SE based mono-exponential T2 fitting will be a good pilot application for this one. Both fitting and Bloch sim are ready to use. Encapsulating `equation` and `blochSignal` into one method like 'synthesizeSignal' would be helpful from implementation perspective. I will experiment ways to achieve this. Thank you for insights! 👍

**Comment by mathieuboudreau** [comment]
No problem – I'm excited to see how it turns out! I know some people in our lab in Calgary had issues acquiring VFA data that made sense (way too high T1 fitted values); I feel like this functionality (to be able to compare both simulated signals) could of helped them immensely during their pulse sequence debugging process.

Good luck!
