### ISSUE TITLE
Time to surgically remove some fat from the repo? i.e. Force deleting/rewriting the history to remove certain old large data files.

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#194]
This morning I tried to do a fresh clone of the repo, which has been running now for two hours (and counting: 30% of objects received).

Even though my current internet speed is not as fast as it would be for you on campus (~10Mbps on a speedtest),  I think part of the issue may be some of the data files that we first included in the repo that have been since moved, i.e. [the Data/ folder](https://github.com/neuropoly/qMRLab/tree/6a9587a45df82c235a5fcf519075ad70f229b6b4/Data), which is still entirely in the git history of the repo (bloating it to over a gigabyte in size, since some data files were rewritten several times).

While it's rarely recommended to rewrite the git history, there are times where it can be warranted (i.e. when [sensitive files were uploaded](https://help.github.com/articles/removing-sensitive-data-from-a-repository/), like passwords). I think that our current situation may warrant such measures, but I'm open to a discussion.

I've already done this in the past to remove data files that included sensitive information from one of my private repos. In that instance, I used the [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) software, which GitHub recommends in some of its help documentation.

Before doing this in the current repo, I think it should be done in a fork and verified. I'm currently using my fork of qMRLab on my personal account as a submodule for for another repo which I want to leave untouched, so I'll create a duplicate copy of the repo (not a fork) and try it out on there. @agahkarakuzu after I create it (whenever this clone is done, I'll send you a note), it would be great if you could fork my duplicate before I make a documented dry-run of this. I'd like to see how the forks of qMRLab will react to this data-purge, if we do it. People who have the repo forked may need to delete it and re-fork it to be in sync, but I'm not 100% sure yet.

**Comment by agahkarakuzu** [comment]
Hi @mathieuboudreau, we ran into same situation two weeks ago while trying to clone qMRLab, it was about 300 MB, hoping that it is not inflated to a GB level 😮. @perone introduced us to the garbage collection concept, which as far as I understand may require a surgeon attention not to incise Git meta files. That's why I noted it down and was keeping for the next meeting, thank you for bringing this up! 

> after I create it (whenever this clone is done, I'll send you a note), it would be great if you could fork my duplicate before I make a documented dry-run of this.

Sure, I will do.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu Great to hear it's not just me – thanks Agah! 

My estimate for the repo size was from an old one I had on my computer, with a lot of branches pulled. I'll update the size of my current clone once it's finished, both pre- and post- pulling all the additional branches.

**Comment by mathieuboudreau** [comment]
3 1/2 hours to clone, and about 416 Mb both pre/post pulling all the branches, so the 1 Gb estimate was off, might have been very old branches/files on there.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu Here's the mirror that I'd like you to fork: https://github.com/mathieuboudreau/qMRLab-clone-playground

If anyone's interested on how this was done, I created a new empty repo on GitHub called "qMRLab-clone-playground", then did the following steps:

```
git clone https://github.com/neuropoly/qMRLab.git

cd qMRLab
git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
git fetch --all
git pull --all

cd ..
mkdir qMRLab-clone-playground
git clone --bare qMRLab/ qMRLab-clone-playground
cd qMRLab-clone-playground/
git push --mirror https://github.com/mathieuboudreau/qMRLab-clone-playground.git
```

**Comment by agahkarakuzu** [comment]
@mathieuboudreau cloning, 100MB almost half way there.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu sorry maybe I wasn't clear, I meant fork it using the `Fork` button on the repo page, not a clone to your local computer. See: https://guides.github.com/activities/forking/

Thanks!

**Comment by agahkarakuzu** [comment]
@mathieuboudreau no problem at all, I did fork now.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu is it possible that the slow cloning is because there is too much traffic on NeuroPoly repos? When I cloned axondeepseg from the NeuroPoly account today, the transfer rate was 10-20 KiB/s, whereas when I cloned my fork of it on my GitHub account, the transfer rate was closer to 1 MB/s.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I am not sure how source codes are actually hosted on GitHub , and how an internal traffic might affect it. I have never experienced "relatively slower" cloning from expectedly busier repositories like Jupyter. 😕

**Comment by mathieuboudreau** [comment]
That's fine – I was just making an "interesting" observation!

**Comment by jcohenadad** [comment]
@zougloub do you have any explanation about [this comment](https://github.com/neuropoly/qMRLab/issues/194#issuecomment-378713312)?

**Comment by zougloub** [comment]
I'm maxing out my 100 Mb/s connection cloning this repo just now...

Not even considering the old `Data` folder, the git repository will keep growing fat because of all the churn on `docs/source/_static`, which clearly contains generated contents, which ideally shouldn't be under revision control (their sources should).
Once everybody has figured out how to stay lean, rather than rewriting the history, I'd advocate archival of the repo, and a fresh start with graft point to the old repo (see https://git-scm.com/book/en/v2/Git-Tools-Replace).

**Comment by agahkarakuzu** [comment]
@zougloub Thank you so much for your suggestion and pointing out the source of the problem we are facing. @mathieuboudreau maybe we can discuss about this in skype meeting?

**Comment by notZaki** [comment]
The repo size was something I noticed when cloning.

The current master is ~23 MB, and roughly ~10 MB is due to docs ( 75% of which is `_static`) 
The other big files are the test results used by coveralls, e.g. `src/Models_Functions/SPGRfun/Parameters/LargeSFTable.mat` is ~3 MB. 

The complete repository with its history, as has been pointed out, is over 400 MB. 
The culprits can be identified by first running (after cd'ing to the repo):
```
git verify-pack -v .git/objects/pack/NAME_OF_BIG_PACK_FILE.idx | sort -k3n | tail -20
```
which will list the 20 largest objects.
The filenames can be found by
```
git rev-list --objects --all | grep ANY_SHA_FROM_PREVIOUS_STEP
```
The old `Data` folder was largely responsible, and running the aforementioned BFG cleaner by:
```
java -jar bfg.jar --delete-folders Data
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```
cuts the repository down to ~145 MB, which is still quite large.
I think that everyone will have to re-clone the repository and delete their old copy if the history is re-written. 
So the archive/fresh start might be the better way.

**Comment by agahkarakuzu** [comment]
#431 `doc` files are no longer in the repository and big binaries are gitignored. A clone of depth 1 now downloads a repo of decent size.
