### ISSUE TITLE
Continuous integration with Matlab instead of Octave

### ISSUE THREAD

**Issue by jcohenadad** [qMRLab/qMRLab#195]
Interesting reading: http://uwethuemmel.com/continuous-integration-workflow-with-matlab-git-and-jenkins/

**Comment by mathieuboudreau** [comment]
Thanks Julien! I actually did read that article previously – I'll discuss with @agahkarakuzu. 

As discussed in issue #59 by Tanguy, this setup would need to be on a dedicated server (at NeuroPoly?), I think.

@agahkarakuzu Have we tried doing a qMRLab Jupyter notebook in Octave yet? I'd be interested to see/play with one to see if it's a feature worth keeping Octave compatibility for, and to see what workflow it could be useful for.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau Yes, I tried qMRLab on Jupyter notebook, the same functionality on Octave can be present on online executable notebooks. The problematic part was to set up all Octave (and its dependencies) configurations for Debian system, since it was the binder OS. 

On your local, you can just add Octave kernel if you are a notebook user and it would work just fine without much hurdle. For online, time consuming fits such as SPGR are subjected to server timeout, whereas faster fits give better use cases.

**Comment by mathieuboudreau** [comment]
Ah I see. Would it be possible to upload one on a branch so that I could see?

More interesting links to compliment Julien's one above Re: Jenkins:

https://thepracticalsysadmin.com/setting-up-a-github-webhook-in-jenkins/
https://blogs.mathworks.com/developer/2015/01/20/the-other-kind-of-continuous-integration/
https://gist.github.com/misterbrownlee/3708738

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I triggered a new build on binder, for Octave it is gonna take some time. I will send you the link when it is completed, then you can try qMRLab on Jupyter notebook online.
