### ISSUE TITLE
Ideas for upcoming hackathons

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#198]
Please throw out any ideas for hackathons here to discuss. I know @agahkarakuzu already has one suggestion for this month's BrainHack.

**Comment by ileppe** [comment]
I could take a look at PSOM

We could also discuss whether it make sense to include MINC support

I was also thinking of getting started on integrating an ASL toolbox

**Comment by mathieuboudreau** [comment]
@ileppe MINC support could be great! Is the best way still to go through NIAK? If so, we'll have to alert the user that they have to open MATLAB from the command-line on Macs to access the MINC tool paths that NIAK uses, not sure how it works for Windows OS's.

**Comment by mathieuboudreau** [comment]
@ileppe I just had a short appear.in meeting with @agahkarakuzu, and we briefly touched on the upcoming hackathon. Taking a look at the schedule, there is a brainstorming session earlier in the day before the actual "hacking" begins.

@agahkarakuzu suggested we wait until that session to decide what to do to see if people have ideas for qMRLab, have insight on how to implement some of the suggestions here, or would be willing to jump on the project. I'm opening my day to help you all out when/if needed, and will likely jump on our appear.in channel if either of you want to work/chat/hack.

**Comment by agahkarakuzu** [comment]
In addition, for BIDS compatibility works:

There is a [matlab file collection](https://github.com/INCF/bids-starter-kit/tree/master/matlabCode) for generating .json files for some data types. These can be used as a start point. 

@jcohenadad  I see lots of value in bringing BIDS compatibility to qMRLab. This is why I would like to use upcoming brainhack as an opportunity to lay the base for BIDS compatibility.  I've seen your suggestions on [BIDS 2.0](https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit#heading=h.x19o2oyegsz2) for MT. I know that specifications are already available for  T1map, T2map and T1rho. Yet, still many qMR specifications are missing. 

How do you suggest (or should) we propose more qMR specifications? For example, would proposing a qmr folder in addition to dif, anat and func be crying for the moon? 

I'd be glad if you can suggest action items that you think are of high priority for BIDS compatibility efforts.

**Comment by spinicist** [comment]
Hi - I have been meaning to get involved with the BIDS 2.0 discussion but have lacked time.

I recently updated QUIT to take most of the input in JSON format - so for instance, with DESPOT1, you need to give a parameter file that looks like:
```
{
    "SPGR" : {
        "TR": 0.01,
        "FA": [5, 10, 15]
    }
}
```
It turns out JSON is pretty nice for small parameter files like this.

I think the biggest issue for qMR + BIDS is the file/folder layout. Currently BIDS seems to be going down the route of being quite specific about how raw data needs to be laid out - I think this may become a headache when the huge variety of qMR methods is considered!

**Comment by agahkarakuzu** [comment]
@spinicist Hi! 

Indeed, json itself is quite useful when considered as a struct that can be read across platforms. In your example, do you generate them manually (e.g. "FA": [5, 10, 15]) ? 

As you noted, file format (NIFTI accompanied by a json) and standardized folder structure are central to BIDS. But this actually can be the solution to deal with the huge variety, although it is going to take some dedicated description effort at the beginning.

What I see is that BIDS definitions are created with mostly DTI and fMRI in mind. They have useful definitions for semantic categorization of these data types (e.g. `task`, `event`). Accordingly, running the same sequence multiple times (`Run` definition) is defined as _an uninterrupted repetition of data acquisition that has the same acquisition parameters and task_. Although repeating same sequence with different parameters is desirable in our case, it is not well captured by current BIDS definitions. 

When I think of a complicated file/folder layout, I imagine an MTsat acqusition for example. Where 1st and 2nd acquisition shares the same FA and differ in MT pulse state, then 3rd and 4th differ in FA, all acquired with the same sequence. Let's think of a case where a user would put all these series under one folder along with two acquisitions for B1 map: 

-- **dicomdir** 
--- ser01 (mt off FA 10)
--- ser02 (mt on FA 10)
--- ser03 (mt off FA 20)
--- ser04 (mt off FA 30) 
--- ser05 (b1 angle 1)
--- ser06 (b1 angle 2)

According to BIDS, these should all go under the anat folder. Hacking the present definitions we can convert this data into:

-- **anat**
--- sub-control01_task-qAcquisition_event-MTsat_run-01.nii.gz 
--- sub-control01_task-qAcquisition_event-MTsat_run-02.nii.gz
--- sub-control01_task-qAcquisition_event-MTsat_run-03.nii.gz
--- sub-control01_task-qAcquisition_event-MTsat_run-04.nii.gz
--- sub-control01_task-qAcquisition_event-B1dam_run-01.nii.gz
--- sub-control01_task-qAcquisition_event-B1dam_run-01.nii.gz

Having JSON files attaining the same name with respective nii.gz., parsing this data for MTsat fitting would be quite easy.  Having qMR specific descriptions would make it even better, instead of using fMRI specific descriptions to hack our way. 

In this scenario, the obvious problem is  to convert from `dicomdir` to `anat ` without causing too much trouble to the users. Fortunately, there is [heudiconv](https://github.com/nipy/heudiconv). Some contribution to their library for the _heuristics of qMR data conversion_ may solve this issue.

I brought MTsat case as an example, it  may not be the most optimal way to organize data. But if we can systematically do this kind of arrangement for all qMR models that we support, we can even tell which mappings are technically possible by validating the raw data provided by user.

**Comment by spinicist** [comment]
@agah - Yes, at the moment I write the input files manually. For the quantitative sequences I have written for GE not all the parameters needed are stored in the DICOM headers.

This is because I generally write sequences to acquire all needed volumes in one series. On GE this is a particularly good approach to ensure all the transmit/receive gains and tuning are the same (manual prescan is a pain to use). To use your MTSat example, I have a sequence that will easily acquire all the MT volumes in one series, and I have structured QUIT to generally use 4D NIFTIs as input. Similarly for DESPOT all flip-angles are acquired in one series, and there’s not an easy way I am aware of to write all the flip-angles into the headers.

It sounds like this doesn’t fit particularly well with BIDS conventions but I wouldn’t want to drop it, it’s incredibly convenient - and for instance it lets you use `mcflirt` for motion compensation which is much more straightforward than running `flirt` on everything individually.

I need to read the BIDS standards more thoroughly but if we could end up with both QUIT and qMRLab working using the same input files that would be amazing.

**Comment by mathieuboudreau** [comment]
>I need to read the BIDS standards more thoroughly but if we could end up with both QUIT and qMRLab working using the same input files that would be amazing.

Agreed - this definitely looks like a valuable thing to pursue! I was also just mentioning to Agah last week that it would be very valuable to test fitting the same data (e.g. VFA) with both qMRLab and QUIT to compare the results.

**Comment by jcohenadad** [comment]
@spinicist thank you very much for chipping in!

@agahkarakuzu in response to [this comment](https://github.com/neuropoly/qMRLab/issues/198#issuecomment-383979009): i think the strategy is to show the BIDS community that there is a critical mass of researchers who are not only doing DTI+fMRI. That implies posting on BIDS2.0 suggestion, participating in various BIDS forums, etc. Regarding the creation of a "qmr" folder, i am not a big fan of it, because it will end up being the same trash can as the anat folder. Also, what happens if people have two different sets of scan for qmr? I would instead follow the same philosophy of the `anat`, `dwi` and `fmri` folder, and add others, such as `mt` (which could be used for qMT, MTsat, MTR, MTCSF, etc.) or despot, etc. But this of course will require some consensus prior to that.

in response to [this comment](https://github.com/neuropoly/qMRLab/issues/198#issuecomment-384059304):
I would not necessarily use the fields task and event, but rather describe the different acquisition parameters with the field acq, as exemplified [here](https://github.com/INCF/BIDS-examples/tree/master/ds000248/sub-01/anat). So in your example it would be something like:
~~~
-- anat
--- sub-control01_acq-MTsat-flipangleXX-TRXX_run-01.nii.gz
~~~

**Comment by agahkarakuzu** [comment]
@jcohenadad Thank you for the suggestions. I agree that we should show more presence in BIDS threads. Departing from your suggestion for `mt`, qMRLab's model hierarchy scheme constitutes a good template. Taking that as a basis, I suggest we write a proposal by following BIDS contribution guideline (quoted below) and attract attention to that in BIDS 2.0. Would you find this idea appropriate and useful?

> - Create a solid draft of your extension by discussing among colleagues.
> - List on the draft who is leading the effort.
> - Share the draft in a form of a google doc (remember to share a link that allows anyone to comment) with the bids-discussion mailing list and ask for comments.
> - Incorporate the feedback, strive for consensus.
> - Help merging the extension into the main specification.

**Comment by spinicist** [comment]
@agah - Yes, my sequences are available to other GE users. GE launched this website https://collaborate.mr.gehealthcare.com/ a couple of years ago - if people join that, they can then request access to the "Software Sharing Group", which involves signing some legal paperwork with GE. Once that's done, I'm allowed to share everything I have (binaries or source code). It's far better than the old way which involved a legal agreement per sequence per site (yuck). Note that someone at your site will have had to go on the EPIC course to get access (I think).

@jcohenadad I agree that a folder roughly per method/technique is the right idea. The tricky bit comes when methods are inter-related, for instance, for qMT you generally need a T1 map. Should the T1 input files go in a separate folder or with the MT stuff? I'd argue for a separate folder.

**Comment by agahkarakuzu** [comment]
@spinicist At our site we use Siemens scanners. But sequence sharing may not be restricted by the Vendor type, have you ever taken a look at [Pulseq](https://github.com/pulseq/pulseq), an open source platform for pulse sequences. I guess custom written sequences can tap into this for sharing across-vendors. 

My choice for inter-related quantifications would be having separate folders. We can have a data explorer that crawls through the directory and check if minimum requirements are met for a certain models.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau @ileppe 

❗️ [THIS IS](https://docs.google.com/document/d/1QwfHyBzOyFWOLO4u_kkojLpUhW0-4_M7Ubafu9Gf4Gg/edit#heading=h.edzhdehfsb1s) ❗️ a highly relevant proposal for adding qMR methods. After mining information regarding the current state of qMR methods in BIDS from the links below, we can populate this proposal with our suggestions.

Here is the [BIDS 2.0](https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit#heading=h.u2m4n7lj0m6g) document that includes Julien's suggestions for changing sequence name for FLASH to a non-proprietary name and adding `magnetization transfer`.

A strategic move would be reading Gorgolewski's answers to the qMR related suggestions/questions to understand the way he approaches suggestions: 

- MP2RAGE, multi echo etc: https://groups.google.com/forum/#!msg/bids-discussion/UrvL4ng3qe8/gb2OjQgmAQAJ

- MT, Multi echo and others: https://groups.google.com/forum/#!searchin/bids-discussion/magnetization|sort:date/bids-discussion/l1NOQceKn0Y/EOWDqczCAwAJ
 
- 💯 Magnetization Transfer: https://groups.google.com/forum/#!searchin/bids-discussion/magnetization|sort:date/bids-discussion/3KQbXfI9BXk/qebtOhe6AQAJ

-  Includes another discussion about MT: https://groups.google.com/forum/#!searchin/bids-discussion/magnetization|sort:date/bids-discussion/IdWe0R8OFyw/uwt7yjxgBgAJ

- By Julien: https://groups.google.com/forum/#!searchin/bids-discussion/magnetization|sort:date/bids-discussion/Xj5yZCLZvyc/ka6TpXm1AAAJ

- SWI thread (also questioning the fitness of anat folder for their purpose): https://groups.google.com/forum/#!searchin/bids-discussion/t1$20mapping|sort:date/bids-discussion/AMQZMCGF9Ek/mimVKOPlAgAJ

- MTR: https://groups.google.com/forum/#!searchin/bids-discussion/quantitative%7Csort:date/bids-discussion/qZpt3qaVmyY/-aZnkHduBwAJ
 
- ASL and other perfusion methods: https://groups.google.com/forum/#!searchin/bids-discussion/quantitative%7Csort:date/bids-discussion/WCkUNCF8rxQ/qlLVUDYSBAAJ

- Announcement that lists new additions: https://groups.google.com/forum/#!searchin/bids-discussion/quantitative%7Csort:date/bids-discussion/1jLKXX-hp7Q/wZmXKGryBAAJ

- https://groups.google.com/forum/#!searchin/bids-discussion/quantitative%7Csort:date/bids-discussion/1jLKXX-hp7Q/wZmXKGryBAAJ

- Rethinking multi echo by Gorgolewski: https://groups.google.com/forum/#!searchin/bids-discussion/julien%7Csort:date/bids-discussion/omJK3sPX9Ok/bJ7bU94ZCQAJ

P.S. Tibor Auer is a name that comes up a lot whenever qMR related topics are discussed.

**Comment by spinicist** [comment]
Thanks @agah, that‘s a lot of reading for me tomorrow.

I’ve not come across Tibo Auer in the literature but looks like he’s at Royal Holloway which is pretty close to KCL, it’s a small world!

**Comment by spinicist** [comment]
@agah / @mathieuboudreau I've had time to read through some of those links / discussions now and what I see there does not encourage me. A lot of the discussion seems to be from people without much experience of quantitative acquisition methods. The BEP001 proposal seems to insist on 3D files only, which is an unnecessary burden in my opinion. Everything in QUIT is structured around 4D files - and my sequences are written to acquired 4D files. Is this something fundamental to BIDS? I assume not as the fMRI files aren't broken down into 3D volumes.

BEP001 also contains barely a handful of example acquisition types - for instance there is no qMT and hence no discussion of offset frequencies. I raise that purely as trying to introduce a filename key for all acquisition parameters is a fool's errand.

I think we definitely all need to get involved in that discussion ASAP!

**Comment by agahkarakuzu** [comment]
Happy that you managed to read some of those @spinicist ! 

> A lot of the discussion seems to be from people without much experience of quantitative acquisition methods.

I can say that the awareness regarding the existence of more than one way of obtaining a certain type of map is not there. 

What I envision is that regardless of the # of dimensions, minimal file name descriptions to the nifti files with comprehensive JSON file attached to them will be enough to decide how to fit that data. Then we can write scripts to parse 3D volumes into 4D qData (or 2D slices to 3D qVolumes), and ensure that parameters match each volume along the quantitative dimension.  Given the inevitable heterogeneity in the accessible scanners and sequences, I think this is desirable.  In addition, # of dimensions does not have to be fixed thereunder BIDS descriptions. 

Upon our brief discussion with @mathieuboudreau, we draw the conclusion that qMT methods are way more tricky to generalize, making boilerplate parsing scheme infeasible. So, qMT may not make the best starting point for discussion compared to the T1, MTR, MTsat, T2 (mono, multiexp) and field maps. 

Advantages of BIDS are:

1) [An online validator](http://incf.github.io/bids-validator/) ensures that user has the correct data
2) It makes it easy to integrate tools to HPC platforms like [open neuro](https://openneuro.org/)
3) Opens up the way to describe conversion heuristics (heudiconv), so that a user can bring their raw DICOM images and get BIDS out. 

It is possible to achieve 3 even without having an accepted BIDS description. Yet, 1 and 2 brings advantages for standardization. To this end, **I agree that we definitely should contribute to those discussions.** 

I think we should divide the problem into smaller pieces, reach an internal qMR committee consensus per method and submit our suggestions.

**Comment by mathieuboudreau** [comment]
@spinicist My 2 cents with @agahkarakuzu  about our involvement in BIDS for qMR methods is that if we have both our softwares follow some of the BIDS recommendation we're going to give even before they official get approved, it'll those give more weight in the discussion. We need to voice our opinions of what we think qMR's needs are, as I agree that it doesn't seem to be mostly qMR ppl guiding the direction of the wind on that project.
