### ISSUE TITLE
[GUI] Bug with 'hold plot' functionality

### ISSUE THREAD

**Issue by ileppe** [qMRLab/qMRLab#210]
Unwanted interaction between plots.
![gui-error-plot](https://user-images.githubusercontent.com/28764708/39932441-26e6fa32-550e-11e8-8459-95be8111312b.png)

Here's how to reproduce it:
1. Load data in viewer (by clicking view)
2. Select a voxel and press 'View Data Fit'
3. Click 'hold plot' on figure that pops up
4. Change slices in the viewer
5. Select another voxel and press  'View Data Fit'

The new slice gets loaded in the held plot and breaks it. We have to somehow maintain the distinction between the plotting areas.

**Comment by mathieuboudreau** [comment]
I haven't been successful in reproducing this bug on Mac OSX 10.12.6 and MATLAB 2017a.

However, using a virtual machine running Ilana's setup (Ubuntu 14.04.5 LTS and MATLAB 2017b), I was able to reproduce it.

![virtualbox_ubuntu-ilana_18_05_2018_20_56_42](https://user-images.githubusercontent.com/1421029/40262061-358a0256-5adf-11e8-8576-2271623d54c7.png)

Not sure yet if the bug is related to the MATLAB version or the OS, but at least it's reproducible.

**Comment by mathieuboudreau** [comment]
Screen capture of the steps I did to reproduce this bug: https://www.youtube.com/watch?v=YEn4YfNcoFM

Note that between steps 3 and 4 described by Ilana, I needed to click the subplot prior to changing volumes for this bug to occur (it didn't for me otherwise).

**Comment by ileppe** [comment]
@mathieuboudreau wow! good job! I guess we'll wait to see how prevalent the bug is for other set-ups...

**Comment by notZaki** [comment]
> The new slice gets loaded in the held plot and breaks it. We have to somehow maintain the distinction between the plotting areas.

This might be fixed by adding the line
```
axes(handles.FitDataAxe);
```
near the beginning of the `RefreshPlot()` function, e.g. before line 910
https://github.com/qMRLab/qMRLab/blob/f03e5a0ead4c0ff94d3c25bd7a4502948b1d22d0/qMRLab.m#L908-L919

I don't use Ubuntu so can't verify whether this actually fixes the bug or not.

**Comment by tanguyduval** [comment]
solved with the new viewer  #296
