### ISSUE TITLE
CLI template for qMR fitting

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#219]
Until BIDS covers useful qMR data descriptions, we need to define a useful convention for this (title) purpose. The initial idea is to have 2 positional arguments for folder locations followed by a JSON file:

`fitfunction input_folder output_folder opt_params.JSON`

If we had a standard for file naming, it would not be necessary, but now we need users to somehow indicate which parameters (Flip Angle, for example) are related to which image sitting in `input_folder`.  I would like to hear your suggestions on this @mathieuboudreau and  especially @spinicist.

**Comment by spinicist** [comment]
I'm not sure what to suggest here. Currently QUIT works on a per-file basis, rather than per-folder, e.g.

`qidespot2 t1_map.nii ssfp_data.nii < params.json`

I haven't got round to fully adopting BIDS yet - although I try to structure subjects/timepoints the BIDS way, for each session I keep everything in one folder as that is how it comes off our scanner. I'm in the middle of implementing `nipype` interfaces for QUIT, once that's finished I was going to take a more in-depth look at BIDS.

**Comment by agahkarakuzu** [comment]
https://github.com/qMRLab/qMRWrappers
https://github.com/qMRLab/qMRFlow
