### ISSUE TITLE
Vectorized inputs for Protocol and Options panels

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#253]
In most cases all protocol inputs are either a single vector, or they build up a matrix where each entry holds a single value that makes sense for a certain pair. 

If an entry is meaningful as a vector, such as image resolution `res = [.5 .5 .5]`, then I don't think there is a way to combine this with other single value entries (TE [1x1], imRes [1X3], FieldStrength [1x1]). A work around is to give a separate label per each vector element such as `res1 res2 and res3`. This is still OK for Protocol panel. 

Same goes for the Options panel. If not a button or dropdown, each option attains a single inputbox for a single entry. In the presence of multiple vector-form entries, all these inputboxes are top-bottom aligned and the panel gets quite crowded. It would be still elegant if there was a way to align them next to each other instead of bottom-top alignment. Is there ?

**Comment by tanguyduval** [comment]
You can add tables in the option part. See mppca denoise model (in PR).

Also, you can have multiples protocols. Example:
Prot.Timing.Te.mat
Prot.Space.Resolution.Mat

Sorry for the typos, writing from my phone

**Comment by agahkarakuzu** [comment]
@tanguyduval thank you! 

I see what you mean. I was trying to relate prots to the image types instead of proliferating new Prot Types. I guess changing the way I parse params is easier :)

**Comment by agahkarakuzu** [comment]
@tanguyduval is it possible to make options conditional? For example, show dropdown menu if the checkbox is selected?

**Comment by mathieuboudreau** [comment]
@agahkarakuzu could you just always show the option, but disable it if the checkbox is/isn't selected?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau do I need to tackle with this in 'Custom_OptionsGUI' ?

**Comment by tanguyduval** [comment]
@agahkarakuzu you can disable an option using ### in the button name.
Please see `qmt_spgr` UpdateFields function
Best

**Comment by agahkarakuzu** [comment]
@tanguyduval I was about to paste that into new class def :D Thank you!

**Comment by agahkarakuzu** [comment]
It seems that I will add some Wiki documentation after finishing qsm model :)

**Comment by agahkarakuzu** [comment]
@mathieuboudreau @tanguyduval I ended up writing more GUI tricks instead of focusing on qsm module, because if I cannot come up with a good options panel design, the rest just won't be OK. Below are what I've added, let me know if you don't like:

i) Added a new joker for visibility property '####' @ `GenerateButtonsWithPanels.m`
ii) Added `getButtonIdx(obj,button)`, `setButtonInvisible(obj,button,bool)`, and `setButtonDisabled(obj, button, bool)` functions to the `AbstractClass` as `private` member functions.  
iii) Also added `linkGUIEvents(obj, checkBoxName, targetObject, eventName)` to make other objects visible/invisible or enabled/disabled with respect to the checkbox state.

**Comment by agahkarakuzu** [comment]
Taking some notes here: 

- Since  one of the options for `qmt_sirfse` has less than 4 chars (`T2r`), a joker with more than 3 chars breaks loading it.

- Jokers for GUI object manipulation should not include underscore, because it is used as a location flag somewhere in the code.

**Comment by agahkarakuzu** [comment]
Taking some other notes, 

Another GUI related issue that may be problematic in the future:

`SetOpt` function under `Custom_OptionsGUI` is called by GUI opening function as long as the `buttons` property of the object is not empty. Although this function appears to have a generic purpose, it mostly serves for curating `FitOptions` panel for `qmt_spgr` without any conditional statements that indicates `Model` in the `appdata` scope is `qmt_spgr`. Instead inference was  based on the existince of `R1MAP` in `FitOptTable`.  This seems like a hack. 

The more I dig deeper in the GUI codes, the more such hacks I find. Don't remember if we have an issue to list similar notes, if there is I will move above one there. 

I will keep working on bringing more modularity to the `GUI` management for easier model additions whilst working on `qsm_sb`.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu 

Comment 1/3 above

i - Could you clarify what you mean by a "joker"?
ii - Cool! Since you added these to abstract class, will do we need to add anything to the Model functions? Or are these optional methods to be used as we want.
iii - Ok! That sounds like it makes sense.

Comment 2/3 above

* This point isn't clear to me, maybe because I don't understand what a "joker" is yet.
* Ok! Add this to the wiki!

Comment 3/3 above

(Set Opt function ... paragraph)

This isn't too surprising to me. qMRLab started off as qMTLab, and all the GUI was built around the qMT models (even though they weren't models at the start).  

(The more I dig deeper in the GUI codes, the more such hacks I find. )

Again, not surprising. GUI development is notoriously difficult, and there has never been a clear design plan during most qMRLab development – things are just added as needed, which has also lead to an extremely cluttered GUI (adding button every time we need something new, instead of thinking of bigger design principles, i.e. don't add a handle to the side a door if you can only push it).

(I will keep working on bringing more modularity to the GUI management for easier model additions whilst working on qsm_sb.)

Ok! Keep in mind if you want to change any of the *.fig files, you need to check(and reserve) if someone is on hold here: https://github.com/neuropoly/qMRLab/issues/258

**Comment by agahkarakuzu** [comment]
@mathieuboudreau 

i) Joker here is three letter special chars ('###') that are prepended to the button names. '###' signals that the UIObject belonging to that button will be disabled. Now I also added  '***' (I initially tried to make it '####' but was not OK) as another joker for show/hide buttons, which are not scoped by a frame.    

ii) This addition is not going to break anything, but for the sake of clarity, we may. `UpdateFields` is the related member function. 

As for GUI, I will start off by writing a wiki doc. Added bunch of in line comments, already. Clarifying what is under the hood should be a good start towards creating a design plan I believe.
