### ISSUE TITLE
stability of fit

### ISSUE THREAD

**Issue by lgazdzin** [qMRLab/qMRLab#267]
Hi,

I am new to using qMRLab (for doing any qMT fitting, really), and I have a question about the stability of the fit. When I'm looking at a single voxel fit, the fitted parameters change every time I press 'update fit' even if I haven't changed any of the input values (I've attached a couple of screenshots to show you what I mean - the only thing that was done between these pics was that I pressed 'update fit'). This seems strange and a bit concerning. Am I misunderstanding something or is the fit unstable for some reason?

As a secondary question, is it possible to set the starting value for R1f to the value of R1 in that particular voxel without fixing R1f to the value or R1? That would be a helpful option.

Thanks!

Lisa G
<img width="825" alt="screen shot 2018-08-23 at 10 49 43 am" src="https://user-images.githubusercontent.com/42647573/44532918-4669b880-a6c2-11e8-85e2-22b8b48e79b1.png">

<img width="824" alt="screen shot 2018-08-23 at 10 50 12 am" src="https://user-images.githubusercontent.com/42647573/44532941-56819800-a6c2-11e8-9ee3-0f248c1bf384.png">

**Comment by mathieuboudreau** [comment]
Hi @lgazdzin !

As for your first point, the reason why the fitted parameters change each time is because some random noise is added to the simulated data points prior to fitting (see: SNR parameter, which stands for signal-to-noise ratio of the no-MT pulse). If you want to simulate with very little noise, try increasing the SNR value (SNR ~ 100,000 should likely make the fitted parameters very stable).

As for your R1f question, this isn't too clear to me. Per Sled and Pike 2001, the R1f value is calculated through the fit not only from the R1 value, but as a calculation between R1 (measured/observed), R1r (typically fixed to 1), f, and kf. See the following equation from that paper:

![123](https://user-images.githubusercontent.com/1421029/44533334-b29cea00-a6cb-11e8-8bbb-2d4c2155e73d.png)

This is how our R1f is calculated throughout the optimisation. As you can see, the initial value will always be different from R1 (measured/observed), because of the initial values of all the other fitting parameters.

Hope some of this information helps!

**Comment by lgazdzin** [comment]
Thanks for replying so quickly!


I hadn't realized that I was looking at simulated data when I was working with the single voxel fit. This makes sense now.


As for the R1f starting value, if it's always determined from the other starting values, then why is there a place to specify a starting value for it and why does this starting value seem to make a difference in the fitting? Does constraining R1f using the R1map simply mean making the starting value the value at that voxel in the R1map or does it mean fixing R1f=R1map? It's not clear in the 'Fitting' options table.


Also - what do the values on the plot title represent? They don't seem to be the starting values or the final fit values -- is this just a display bug?


Thanks again.

________________________________

**Comment by lgazdzin** [comment]
Actually, I'm concerned that I've misunderstood something. Is the data used in the qMR simulator taken from my actual voxel data or is it generated some other way? Is the way to actually look at how well my data is being fit to look at the fit by pressing the 'view data' button under 'sanity check'?


Is there a user manual of sorts that may answer these questions without my having to both you with them? I've watched the tutorial, but it's fairly general.


Thanks again.

________________________________

**Comment by agahkarakuzu** [comment]
> As for the R1f starting value, if it's always determined from the other starting values, then why is there a place to specify a starting value for it and why does this starting value seem to make a difference in the fitting?

hi @lgazdzin  can you seed you random number generator and try again? 

https://www.mathworks.com/help/matlab/ref/rng.html

**Comment by mathieuboudreau** [comment]
@lgazdzin No problem – we always welcome valuable user feedback! Graphical user interface development can be very challenging, particularly when trying to offer all the options our users ask us for.

I've uploaded a video on how to fit qMT data for a single voxel within your image volume, which is what I think you are trying to do: https://www.youtube.com/watch?v=Tb6Nqo0KF40&feature=youtu.be%3Fvq%3Dhd1080. I admit it could be made clearer. The options on the left (Multi Voxel, Single Voxel Fit, Sensitivity Analysis) all deal purely with simulated data.

As for R1f, you can select between using the R1map or fitting for it without information from the R1map (not recommended though, the qMT literature makes it clear that this will lead to unstable qMT fits) in the options panel:

![r1f](https://user-images.githubusercontent.com/1421029/44536904-de23d280-a6d3-11e8-82eb-9163c70bf5fc.png)

Note that if you select "Use R1map to constrain R1f", then the start value for R1f changes to "R1MAP" to indicate there can be no starting value set (as I said, it's calculated from the other parameters). If you uncheck it, then you are allowed to set a starting value. If your options panel does not look similar to mine, then it's possible you are using an older version of qMRLab, and should download the latest release (v2.2.0): https://github.com/neuropoly/qMRLab/releases

Also, just out of curiosity, would you mind sharing who you are/which lab/which institution you're from? (it's ok if you're not comfortable with that, we are jus always curious to know who picked up our software 😃 )

**Comment by lgazdzin** [comment]
Oh, I see. I think this is sort of what I was hoping for - that the R1map would be used to set the initial value for R1f. I understand better what that option means now.


I'm in Anne Wheeler's lab (a lab looking at TBI using neuroimaging - I'm working with mouse data) at SickKids. I'm sort of using qMRLab to double check the fitting that I've been getting with my own code implementation of one of the qMT models and so it's important that I can set the initial values the same as I do in my own code!

It's also important that I'm able to see what the output parameters are for the single voxel fit. The plot title is incomplete and I'm not sure if the values are correct. Is there another way to see what the output parameters (F, R1f, kr, etc) are for a single voxel 'sanity check' fit (without having fit the whole masked image and therefore not able to look at the same voxel on the different maps)?



________________________________

**Comment by mathieuboudreau** [comment]
@lgazdzin Yes I noticed that too re: incomplete values in the title. I'm not sure why that is happening. @agahkarakuzu do you have an insight? The other option might be to use the command-line interface to fit for a single voxel – is it possible to do so @agahkarakuzu ? Or @tanguyduval ?

I know that if you fit the entire volume (by clicking the Fit Data button), then when that's done clicking the "Save results" button, you will get a *.mat file saved with a structure variable in it, which will contain the volumes of all fitting parameters somewhere in there. But I understand that you might just want to do a single voxel at a time. It may be possible to quickly hack the code so that the output of said parameters are shown in the MATLAB terminal instead of the title, do you (@agahkarakuzu or @tanguyduval ) know which snippet of line should be added and where to do this?

Are you also using the Sled and Pike fitting model in your own code? There's other options you can use in ours (e.g. Ramani, Yarnykh), but I'm less familiar with them in practice.

> I'm in Anne Wheeler's lab (a lab looking at TBI using neuroimaging - I'm working with mouse data) at SickKids.

Cool! My UWO MSc supervisor was Giles Santyr – I think he's at Sick Kids now too 😃

**Comment by tanguyduval** [comment]
it seems that kf and R1f are inverted on the plot title... and round... Yes
this is a bug
As for the command line, you can use the copy/paste example of method fit
in qMRusage('qmt_spgr')

Thanks for the feedback!

>

**Comment by tanguyduval** [comment]
- [ ] correct plot title: order of variables is wrong

**Comment by mathieuboudreau** [comment]
@lgazdzin @tanguyduval I think here is the title bug:

https://github.com/neuropoly/qMRLab/blob/12014627676672499c3e8d77a247ea136609b020/src/Models/Magnetization_transfer/qmt_spgr.m#L305-L307

@lgazdzin after this code block above, if you want to display the fitted parameters, just add:

`disp(x)`

in that file at that location, and it should display in the terminal like this:

```

          F: 0.1527
         kr: 10.8292
        R1f: 0.8981
        R1r: 1
        T2f: 0.0249
        T2r: 1.2670e-05
         kf: 1.6534
    resnorm: 0.0034

```

**Comment by lgazdzin** [comment]
Small world! I was also at UWO for grad school (perhaps we actually know each other by face but not by name!). Yes, Giles is here at SickKids - his office is down the hall from my desk.


I'm actually trying to use the Yarnykh model in my own code, but the fit is not good (hence why I wanted to try qMRLab and see if the problem is with my code or with the model). It may be a bit of both - the model doesn't fit my data so well in qMRLab either, although the fit isn't quite the same as I get using my code. The Sled and Pike CW model seems to fit my data better. I may chat with John (Sled) about this and see what he thinks.


In any case, thanks so much for your help today! Slowly, but surely, we'll get this sorted out ...



________________________________

**Comment by mathieuboudreau** [comment]
@lgazdzin Cool!

No worries – I hope you get around debugging your issue! qMT has so many options... One issue that some colleagues in Calgary (Ethan MacDonald and Melany McLean in Bruce Pike's lab) hit were with their MT pulse – they found out that because their Gaussian pulse wasn't apodized and was a bit wide (they ended up using a Gaussian-Hann pulse which worked better), they were saturating a wider range of frequencies than the model is built for, and that was negatively affecting their fit. Just thought I'd share that out there.

Also note, in case that it wasn't clear, that you have to normalize your data (divide your data points by the no-MT image) prior to loading them into qMRLab, in case that wasn't clear either. (our demo data is pre-normalized). This information

Good luck – and don't be shy open any more issues!

**Comment by lgazdzin** [comment]
That's interesting about the pulse. I'll have to give that some thought.


And yes, my data is already normalized.

________________________________
