### ISSUE TITLE
New README.md 

### ISSUE THREAD

**Issue by agahkarakuzu** [qMRLab/qMRLab#281]
In the meeting we decided to add qmrlab.org here. Now there is more, I changed `README.md` quite a bit. You can see the new version on my `stats` branch.

**Comment by mathieuboudreau** [comment]
The resolution of you GIF is too low, it doesn't look nice. Also, if you click the download button on it, it just redirects to the website, where you see the same screen, instead of actually downloading. The behaviour is not clear for new users. If you want your animation there, I'd place it without the the download button. 

I personally find GIFs in readme's a bit gimmicky, but pass it by Nikola and if that's the way he wants it to look, we can roll with it.

As for the new badges, I'd place them all aligned, not in two different paragraphs. The follow button is also very confusing, as it shows the number "387" right now, but we only have 99 followers. 

Maybe this page should be brought up to discussion at the next lab meeting? We could compare with other softwares of similar calibre, and see what design principles went into theirs.

**Comment by mathieuboudreau** [comment]
Also, is your `stats` almost ready for a merge? If it's going to be a while, we might as well create the new README its own branch.

**Comment by agahkarakuzu** [comment]
PR: #289

**Comment by agahkarakuzu** [comment]
#289
