### ISSUE TITLE
Actual Flip Angle Imaging (AFI)

### ISSUE THREAD

**Issue by mathieuboudreau** [qMRLab/qMRLab#387]
We could use this function from the repo I just made public from my PhD B1 paper as a template: https://github.com/mathieuboudreau/B1Paper_Analysis/blob/master/src/b1/fitDataAFI_es.m

It needs cleaning up, but it should be a quick model that we can include.

**Comment by mathieuboudreau** [comment]
This branch has been assigned to @jvelazquez-reyes .

Here's some additional details from our video call today:

**Papers**
* https://onlinelibrary.wiley.com/doi/epdf/10.1002/mrm.21120

**Model checklist**
* [ ] Create new model that fits AFI data
* [ ] (Optional) Create simulations from paper equations
* [ ] Add an option to Parallelise the voxelwise computation code if the user has multip CPU cores
  * (For the qMRLab folks, yes technically it would be quicker to simply linearise this calculation for the AFI equation by setting voxelwise = 0, however we want to test this feature here before trying it on bigger models like qMT)

**Blog post details**

* [ ] Create a Jupyter notebook that runs an AFI example (you can ask @agahkarakuzu for the qMRLab Dockerhub image setup)
* [ ] Create interactive figures with Plot.ly (you can ask @mathieuboudreau as he's done several examples for blog posts already)
* [ ] Write a short blog post about AFI that will be hosted on qMRLab

@jvelazquez-reyes I'll upload an example dataset to OSF that you can use to test run your model(@nstikov gave me permissions to upload one I acquired on him for my PhD project).

**Comment by mathieuboudreau** [comment]
The AFI dataset has been uploaded here: https://osf.io/csjgx/

**Comment by jvelazquez-reyes** [comment]
Hi Mathieu!

I created the b1_afi model and I tested it on the dataset you uploaded. With the Parallelize option off (and voxelwise=1) it works perfectly with GUI and CLI.

However, I haven't managed to complete a test with the Parallelize option. I tried the following with the Parallel Computing Toolbox from Matlab (R2017b):

- I distributed the arrays to work them with 4 local workers
- I also tried a batch process to run a function (which process the AFI data) in my local cluster with 4 workers. I tried nesting the function within the fit function, also as a local function (within the methods) and as an Anonymous function.

None of that worked. Apparently, it started running but somehow it's extremely slow.

Perhaps you could give me a hint on how to proceed, or maybe you were thinking of another way to approach the Parallelize option.

I created a version branch (update_2.5.0) where I placed the progress (b1_afi.m). Do you want me to push it so that you can take a look at that issue? Or do you want me first to try out something you might have in mind?

**Comment by mathieuboudreau** [comment]
Great, thanks for the update @jvelazquez-reyes ! Yes, please push your branch as frequently as you can - that we can try it ourselves and give some input/assistance.

**Comment by mathieuboudreau** [comment]
@jvelazquez-reyes thanks for pushing your branch. I created a pull request (#395) so that we can more easily track changes there as they get pushed. I recommend you do a `git pull` in your branch before making more changes, as we might push some changes too. We should move the discussion there for the time being.

Thanks!

**Comment by agahkarakuzu** [comment]
CI test passes and secured with assertion checks. I matched the OSF data with the default (polynomial) filtering mode. Thank you @jvelazquez-reyes for the work!
