### ISSUE TITLE
Missing negative sign in MT-SPGR equation

### ISSUE THREAD

**Issue by rixez** [qMRLab/qMRLab#448]
Hello, and thank you for the awesome qMR library! I was reading through the codes of qMT and it seems like the equation for the A matrix is missing a negative sign: https://github.com/qMRLab/qMRLab/blob/ccea5bd6454b1ca464bdd4686dcfbb5b368d7b74/src/Models_Functions/SPGRfun/functions/SPGR_Srp_fun.m#L80
## Expected Behavior

Following the convention in the qMTLab paper and Sled 2000 (jmre.2000.2059), all terms in the matrix are negative of the ones in the codes. I haven't looked at other functions so there might have been correction elsewhere. For comparison, the Bloch equation in https://github.com/qMRLab/qMRLab/blob/ccea5bd6454b1ca464bdd4686dcfbb5b368d7b74/src/Common/sim/Bloch.m#L1 is the same as in the papers.

## Current Behavior

There is small difference between the ODE solution to the Bloch equation and the steady-state analytical equation from the equation above.

## Possible Solution

Append a negative sign to the A12 matrix.

Thank you!

**Comment by agahkarakuzu** [comment]
Thank you so much @rixez for pointing out this issue! We will look into this quickly.

@mathieuboudreau are you available for reviewing this quick fix?

**Comment by spinicist** [comment]
Hello,

@rixez how big is the discrepancy between the ODE solution and the analytic equation?

The analytic solution includes a minus sign inside the exponential on the very next line: https://github.com/qMRLab/qMRLab/blob/ccea5bd6454b1ca464bdd4686dcfbb5b368d7b74/src/Models_Functions/SPGRfun/functions/SPGR_Srp_fun.m#L81

Have you tried adding the proposed minus signs and seeing what happens to the analytic solution?

**Comment by mathieuboudreau** [comment]
I'll look into the code/paper this morning. Will get back to you ASAP.

**Comment by mathieuboudreau** [comment]
Ok, so I went through the derivation of the equations again, and I have one conclusion and one hypothesis,

## Conclusion

I agree with @rixez that the matrix **A** in our code is the negative of the matrix that can be derived from the equations currently in the Sled2000 paper.

## Suspicion

I suspect that there may be a typo in equation A1 of  the Sled2000 paper. There is a negative missing in front of the *AM(t)*  term, in order for the subsequent solutions to the equation to make sense (to me at least, but I might be totally wrong as I've only briefly reflected on this). This could also explain why our code appears to accurately fit qMT parameters that are both simulated and measured on scanners.

Here is my derivation and quick explanation. I'd love further input in this, particularly from @spinicist as I know he's dealt with qMT solutions in a lot of different scenarios. We could also reach out to John (Sled) and/or Ives, as they wrote the code that JF Cabana (the one who implemented the initial qMTLab) prepared here that we've been discussing.

If what I suspect is incorrect, the alternative would be to 1) change the sign in the equation that @rixez pointed out and see if all the solutions/fitted parameters break down/diverge, and if they do (hopefully) then that means that there is likely a rogue negative sign that is compensating for this different in the terms of A somewhere in our implementation, and so we could do a cleanup job of that for it to be more consistent with the paper's equations.

![frame_apngframe1](https://user-images.githubusercontent.com/1421029/127336176-9cfc8a6c-f20b-4a12-9913-d39aa521f4bb.png)

![frame_apngframe2](https://user-images.githubusercontent.com/1421029/127336199-a2a593c7-8845-4404-8ca1-cc0b1101f670.png)

![frame_apngframe3](https://user-images.githubusercontent.com/1421029/127336225-f339a920-3970-4a2c-a697-134ecef2b46a.png)

**Comment by mathieuboudreau** [comment]
I fit the sample data with the original implementation (currently in master branch) and also by making A12 and A0 negative.

## Original implementation

<img width="803" alt="Screen Shot 2021-07-28 at 11 35 12 AM" src="https://user-images.githubusercontent.com/1421029/127345751-d209ee46-c1c5-4f3c-9ef7-e65f5f9dbd6b.png">

## With A-parameters changed to negative values

<img width="803" alt="Screen Shot 2021-07-28 at 11 59 28 AM" src="https://user-images.githubusercontent.com/1421029/127345835-b46d36bc-9240-43bb-b478-ac3817797835.png">

## Thoughts

The fits didn't break down as much as I would have suspected. Overall, the change in sign shortens the F parameter substantially, but still within normal range I think.

Here are the other parameters for each case

## Other parameters (original case)

<img width="803" alt="Screen Shot 2021-07-28 at 12 04 30 PM" src="https://user-images.githubusercontent.com/1421029/127346542-3cd63216-c30c-4ecd-97ce-e480f57ca743.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 04 37 PM" src="https://user-images.githubusercontent.com/1421029/127346555-dc686d1e-d6ee-4240-9b8a-f7ce9586e81f.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 04 45 PM" src="https://user-images.githubusercontent.com/1421029/127346568-35bbb875-8888-4b2d-b6cb-be9a360cc4a0.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 04 52 PM" src="https://user-images.githubusercontent.com/1421029/127346576-add4d15b-5787-4e20-a1b8-f19cf7fccaba.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 05 00 PM" src="https://user-images.githubusercontent.com/1421029/127346589-322a1937-5099-4ad6-aca9-44b34227820b.png">


## Other parameters (negative value case)

<img width="803" alt="Screen Shot 2021-07-28 at 12 02 41 PM" src="https://user-images.githubusercontent.com/1421029/127346281-e38dad32-1885-4091-9cf4-ce15811a583d.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 02 46 PM" src="https://user-images.githubusercontent.com/1421029/127346303-2d672b2a-7031-404a-9d1e-3b27691de02c.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 02 52 PM" src="https://user-images.githubusercontent.com/1421029/127346316-ede860f8-58d3-4ad8-bcc9-455740ee8618.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 02 57 PM" src="https://user-images.githubusercontent.com/1421029/127346329-13775f7e-970b-4f13-a7ce-9204c6c3bb0f.png">
<img width="803" alt="Screen Shot 2021-07-28 at 12 03 05 PM" src="https://user-images.githubusercontent.com/1421029/127346337-f6d81e5d-3e93-45c2-9d1a-336a7f4a3cbc.png">

## Additional thoughts

For the other parameters, resnorm improves with the negative value case, however T2f completely diverges, which could be a sign that this solution isn't proper. kr also changes, but this is likely due to the tug-of-war relationship it has with F, so since F changed in one direction, kr also had to be changed in the fit as well.

**Comment by spinicist** [comment]
Hi @mathieuboudreau 

I'm also surprised that inverting the matrices doesn't change the fitting more. But it looks like there is an upper bound of 500 ms on T2_f? I guess if that bound was removed it would go even higher and mess the maps up more? Regardless, those values of T2_f are clearly wrong.

I think the important thing is to focus on is that dMz/dt = -R1 Mz + R1 M0. The way I look at the current code, the A12 matrix is indeed written with the negative of that, but the minus sign inside the `expm` call will cancel that out. I think it's a case of whether you want to write `y = expm(A*t)` or `y = expm(-A*t)` (or their equivalents).

I'd expect some minor differences between an ODE and the analytic solution. The question is how big those differences are.

**Comment by mathieuboudreau** [comment]
Thanks a lot of your insights @spinicist. I've worked out the case of simple relaxation as you suggested, and it convinced me that the current implementation in our code is correct. See below

![Doc1](https://user-images.githubusercontent.com/1421029/127367725-1b15ac78-a858-481e-9ec6-79e7ba6272f6.png)

**Comment by mathieuboudreau** [comment]
As for your last point,

> I'd expect some minor differences between an ODE and the analytic solution. The question is how big those differences are.

I think there is a slight misunderstanding (or miscommunication on our part). I believe what we call the analytic solution is actually the analytical approximation solution to the equations which also uses ODEs get the solution (if I recall, we use ODEs to get intermediate solutions, e.g. the free precession and continuous wave segments of the equations); it is how Sled developed his solution to the Bloch-McConnell in the pulsed MT case (by creating constant segments events) in order to avoid numerically solving the entire sequence.

In our simulations, we do have two options though; using this steady-state analytical approximation vs. a full Bloch simulation (of each TR).

**Comment by mathieuboudreau** [comment]
@rixez please chime in to confirm if our explanations make sense to you and you agree with them.

**Comment by rixez** [comment]
Thank you @mathieuboudreau, @spinicist for the discussion! After looking at the paper and playing with the codes a bit more, I agree with @mathieuboudreau comment that there is a typo in the Sled2000 paper. It wouldn't make sense with the negative sign in the exponential with the formula in the Sled paper as the `expm(-At)` term would blow up if t -> inf. I think the implementation in qMRLab is correct.

For posterity, this is a comparison between numerical Bloch simulation and the analytical solution with and without the negative sign.
Without negative sign (qMRLab version)
![image](https://user-images.githubusercontent.com/33406397/127414767-c7377eab-8894-4e04-91b3-6c323a763e62.png)
With negative sign
![image](https://user-images.githubusercontent.com/33406397/127414899-2d7cbeb9-934b-4afd-a79f-b9b8a446f4a0.png)

The ODE result approaches the analytical solution in the qMRLab version so I think it is correct. I think in a prior simulation with a different set of parameters the second version gives the same result as the ODE solution, which confuses me about the validity of the equation.

Thanks again for your help and discussion @mathieuboudreau, @spinicist, @agahkarakuzu. I will close the issue now.

**Comment by mathieuboudreau** [comment]
Excellent! This was a fun discussion; thanks for bringing this apparent discrepancy to our attention @rixez. And also thanks @spinicist for jumping into the discussion and sharing your great insights.
