### ISSUE TITLE
Issue running the Jupyter notebook on T1-mapping VFA

### ISSUE THREAD

**Issue by jcohenadad** [qMRLab/qMRLab#466]
I'm trying to run [this notebook](https://qmrlab.org/jekyll/2018/12/11/T1-mapping-variable-flip-angle.html) in myBinder, and I observe the following issue:

![image](https://user-images.githubusercontent.com/2482071/166054827-868deda4-5ff4-4e79-9d87-5aeab699ec56.png)

 
## Steps to Reproduce

1.
1.
1.
1.

## Possible Implementation

another (related) issue, is that when clicking on 'code', it brings to the qMRLAB repos, whereas it should point to the notebook-- same for "download"

**Comment by jcohenadad** [comment]
maybe related to this?
![image](https://user-images.githubusercontent.com/2482071/166057143-c12bdd32-0258-4cbf-a1f5-722ef233ca59.png)

**Comment by agahkarakuzu** [comment]
@mathieuboudreau looks like yet another all env described line by line in a Dockerfile issue. 

We should fetch 98% of these dependencies from a base qmrlab docker image that's stable and not subjected to binderhub's time-dependent repo2docker build instabilities. What do you think?

**Comment by mathieuboudreau** [comment]
@jcohenadad I'm on my phone right now, but as a temprorary alternative I recommend you use the Jupyter Book version of this content (http://qmrlab.org/t1_book/01/vfa_blog/VFA_SignalModelling.html), which is more up to date and the MyBinder notebooks appear to be working as expected.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
From: Julien Cohen-Adad ***@***.***>
Sent: Friday, April 29, 2022 4:24:43 PM
To: qMRLab/qMRLab ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qMRLab/qMRLab] Issue running the Jupyter notebook on T1-mapping VFA (Issue #466)


I'm trying to run this notebook<https://qmrlab.org/jekyll/2018/12/11/T1-mapping-variable-flip-angle.html> in myBinder, and I observe the following issue:

[image]<https://user-images.githubusercontent.com/2482071/166054827-868deda4-5ff4-4e79-9d87-5aeab699ec56.png>

Expected Behavior
Current Behavior
Possible Solution
Steps to Reproduce

  1.
  2.
  3.
  4.

Context (Environment)
Detailed Description
Possible Implementation

**Comment by jcohenadad** [comment]
> [@jcohenadad](https://github.com/jcohenadad) I'm on my phone right now, but as a temprorary alternative I recommend you use the Jupyter Book version of this content (http://qmrlab.org/t1_book/01/vfa_blog/VFA_SignalModelling.html), which is more up to date and the MyBinder notebooks appear to be working as expected.

Thank you for your reply, Mathieu. indeed, I started there, but then I wanted to actually modify the plots (show the ratio of the WM and GM evolution curves) in the context of the MRI course I am giving, so for that I need to be able to edit and run the code

**Comment by mathieuboudreau** [comment]
@jcohenadad in the jupyter book link I shared, there is a "Launch Binder" button at the top of each page, and clicking that will open that notebook in a MyBinder session where you can edit and run the code.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jcohenadad** [comment]
oh! I see, i thought that link would bring me to the book, but it does not. This is awesome! thank you so much. I was in the middle of recreating a notebook and struggling with dependencies, octave conversion to python, etc. 😅

**Comment by mathieuboudreau** [comment]
Great! Let me know if you need a hand with anything else re: my notebook/binder/whatever

**Comment by mathieuboudreau** [comment]
@jcohenadad I fixed the original issue in this PR https://github.com/qMRLab/t1_notebooks/pull/23. I think the issue stemmed from very (very) old versions of pip/setuptools inside the docker image, which couldn't resolve some of the dependencies correctly after a rebuild the last time that MyBinder cleared their cache.

@agahkarakuzu I agree that considering these notebooks are "completed", I could package my dockerfile up and upload it as an image on Dockerhub that can be pulled, so that the next time MyBinder clears this cache I'll be using the same container instead of a rebuild container from the Dockerfile.

**Comment by mathieuboudreau** [comment]
p.s. thank you so much for alerting me that the builds were broken @jcohenadad ! 🙏

**Comment by agahkarakuzu** [comment]
We can set CRAN tasks to send automated binderhub build requests if you want (e.g. once a week), so it'll notify when something goes wrong.

**Comment by mathieuboudreau** [comment]
Great idea! I think though that even that wouldn't have catched this problem ; one of the pip install fails but the build continued and finished "succesfully", which is why Julien was able to get inside the notebook on the mybinder session even though it was broken :/
