### ISSUE TITLE
Add module for MTR

### ISSUE THREAD

**Issue by jcohenadad** [qMRLab/qMRLab#90]

**Comment by mathieuboudreau** [comment]
@gab-berest not sure if you've already started working on this module, or have already decided on how to implement it, but I was just thinking this morning that this module could be a great candidate for inheriting the SPGR module. Since MTR is basically a qMT protocol with a single protocol point (1 MT alpha & 1 offres freq, and 1 MT-off), you could take advantage of the simulation methods already in SPGR to power simulations of MTR, and then override the necessary methods (e.g. fitting) for it to work as an MTR module. 

If don't have experience inheriting Matlab classes (I don't think any modules here use it yet), it's fairly easy, I've written a gist example here: https://gist.github.com/mathieuboudreau/a641a3b39065157c5e0c45588551a25e

Since no methods are overriden, that example simply creates a new module called MTR but otherwise is identical to SPGR.

The major benefit of inheriting the qMT SPGR class in this module, particularly for the simulation aspect, would be that any speed improvements/bug fixes/new pulse sequence features in the SPGR simulations would be automatically applied here.

**Comment by mathieuboudreau** [comment]
I just noticed today that MTsat doesn't have a simulation component implemented - if it also inherited from SPGR, it could likely also be easily implemented as well.

**Comment by tanguyduval** [comment]
Methods with voxelwise = 1 do not have simulations because usually, it's simply a ratio between 2 or more images, and the sensitivity can be computed analytically. But I agree we could propose something (e.g. use Block equations).

**Comment by mathieuboudreau** [comment]
Ahh I see. Yeah, it could be useful to use the MT SPGR module to simulate the signal using the base qMT properties (e.g. F, kf, etc), to be able to investigate how changes in those would impact the MTsat/MTR measurements, if for anything else to be an educational exercise. 

I was meeting with a post-doc in St. John's today who actually wants to do MTsat for an MS study, but doesn't have a lot of MR experience, so I suggested this software to him. It could be useful for people like him to play around with prior to acquiring the data, to get a sense of things.
